version: '3.4'
services:
  db:
    image: leonardograselalmeida/mysql-rest-with-spring-boot-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  rest-with-spring-boot-udemy:
    image: leonardograselalmeida/rest-with-spring-boot-udemy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    working_dir: /RestWithSpringBootUdemy
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - .:/RestWithSpringBootUdemy
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run -e
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge